#!/usr/bin/env bash
#transfer a file from our client to a server
#
#the script accepts 4 parameters
#- The path to the file to be transferred
#-The IP of the server we want to transfer the file to
#-The username scp connects with
#-The path to the SSH private key that scp uses
#
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="ubuntu"
ssh_key_path="~/.ssh/id_rsa"

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/

# Check if the scp command was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully"
else
    echo "Error transferring file"
fi

